### ISSUE TITLE
path_builder::get_current_point() wrong

### ISSUE THREAD

**Issue by BongoVR** [mikebmcl/N3888_RefImpl#30]
The implementation of path_builder::get_current_point() is wrong since it dereferences _Data.crend().

Possible fix:
Simply return _Current_point which already contains the information requested:
point path_builder::get_current_point() {
	assert(has_current_point());
	return _Current_point;
}

Cheers

**Comment by mikebmcl** [comment]
Thanks for the report! I am applying your suggested fix.

I also thank you because you made me aware of another "bug". All current development is focused on the N4073-successor branch. This bug was fixed somewhere in there. Also, the class itself has been renamed to `path_factory` and the function itself is now `path_factory::current_point()`. Once I switched branches I basically ignored the master (i.e. N4073) branch, but your report made me realize that for fixable bugs (like the one you reported), I probably should have made the effort to backport them.

Since my focus has been (effectively) exclusively on N4073-successor for a very long while now, and since this whole standardization effort is a work-in-progress, I think that sometime in the near future I will create a new branch called something like "N4073" from the current master branch and then merge all of the changes from N4073-successor into master and make any updates to the README, etc., to explain the reorg of branches. I'm not sure when I'll do it, but it you made me realize it's something that should be done.

Best regards,
-Mike
