### ISSUE TITLE
Remove extend none

### ISSUE THREAD

**Issue by jrmuizel** [mikebmcl/N3888_RefImpl#33]
This extend mode, despite being the default in cairo, is rarely what people want (interpolating to a border of transparent black). The concept of extend none does not exist in most other graphics APIs (CoreGraphics, Direct2D, Direct3D, HTML Canvas) and so it feels like adding it to this standard adds undue implementation burden.

**Comment by mikebmcl** [comment]
Sadly, I know for sure that D3D does impose limits for GPUs that are "10Level9': https://msdn.microsoft.com/en-us/library/ff476876(v=vs.85).aspx (see footnote 3, which discusses situations in which non power-of-2 textures are allowed).

That said, the latest Steam Hardware & Software Survey - http://store.steampowered.com/hwsurvey - provides good evidence for changing the default to repeat and to forcing implementations to switch to software rendering (or some other workaround) as needed. I need to think on it a bit more but I'll likely make that change.

Even so, I think extend::none has value to developers. You have said that the concept "does not exist in most other graphics APIs". I know that D3D in D3D11_TEXTURE_ADDRESS_BORDER - https://msdn.microsoft.com/en-us/library/ff476256(v=vs.85).aspx - where the sampler's D3D11_SAMPLER_DESC::BorderColor is set to transparent black will provide it. I expect the others provide some way to accomplish it since cairo provides it, but I would have to do some research to see if it's API-provided or a software solution.

Regardless, thank you for your feedback!

Best regards,

-Mike

**Comment by jrmuizel** [comment]
Ah, I wasn't aware that D3D had texture borders. OpenGL ES does not unless the EXT_texture_border_clamp extension is available.

**Comment by mikebmcl** [comment]
The none value is staying. As of P0267R4 - http://wg21.link/P0267 - "extend" has been renamed to "wrap_mode" and its value is now part of the "brush_props" class (a result of the change to a stateless API design).

For now, the default value for all brush types is none, but I may change that in R5 due to, e.g. http://store.steampowered.com/hwsurvey . I want to research a bit on how OpenGL ES 2.0 hardware would react to a change to, e.g. wrap_mode::pad or wrap_mode::repeat .

This is headed towards a TS (i.e. not incorporated into the C++ standard itself) so setting "lofty" goals like wrap_mode::repeat and getting feedback on whether or not this is acceptable would become part of the desired feedback for the TS.

I'm closing the issue for now, but please feel free to add additional comments. I may not respond to them but definitely will read them.

Thanks!
