### ISSUE TITLE
Graphics backend implementations need to be isolated

### ISSUE THREAD

**Issue by GravisZro** [mikebmcl/N3888_RefImpl#37]
I've looked at the proposal and from what I can tell from both the proposal and this reference implementation, either the entire graphics subsystem has to be reimplemented for every graphics renderer or graphics backed implementations would be integrated into the STL/libstdc++/libc++.

Instead of being integrated or have entire subsystems reimplemented several times, the specification should isolate the rendering in some manner.  I suggest making an interface class for graphics backends to implement.  This would minimize the amount of duplicated code (and accidental bugs) while maximizing the number of possible graphics backend implementations (unlimited).

If this is already the case, please update the spec and reference implementation and tell me so I can stop stressing out about this.

**Comment by mikebmcl** [comment]
The link that was here earlier today was to an older version of the paper (P0267R2). I fixed it so that the link now always points to the current version. Here's a link to R4 (the current version): [P0267R4](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0267r4.pdf). It may address your concerns in that it has moved significantly towards being a stateless API.

As far as:

> I suggest making an interface class for graphics backends to implement. This would minimize the amount of duplicated code (and accidental bugs) while maximizing the number of possible graphics backend implementations (unlimited).

the only thing the proposal specifies is an API. There are requirements on the implementation, but the details of the implementation are left up to library vendors (and anyone else who feels like implementing it). Excluding the display_surface, the current proposal can be implemented with software-based Bresenham algorithms, OpenGL, OpenGL ES (possibly a minimum of ES3 because of sRGB), Direct3D, Direct2D, Vulkan, etc.

The display_surface class is a special case. The intention with it is to avoid delving into whether the program is running on a windowing environment (Windows, X11, etc.), on a smartphone or tablet (more specifically a one fullscreen app at a time environment), or something else entirely. So the language for it is intentionally vague. When text rendering and (eventually) input are added, this class, or a class that derives from it, will be the easy way to accomplish anything from a 10 line graphical "hello world" to a simple app where the developer doesn't need/want to worry about the details of the event loop.

On the repo for P0267 itself, the issue of how to design an API where the dev has a window already and wants to be able to use this to draw to part of it is open - https://github.com/mikebmcl/io2dts/issues/6 . I have some thoughts on that, but nothing I've had a chance to try out yet.

This reference implementation will be R4 current within the next day or two. There are only a few minor parts that are missing.

**Comment by GravisZro** [comment]
You seemed to have misunderstood or somewhat dodged my specific questions, so I'll try to be more clear.

> ... the details of the implementation are left up to library vendors...

Do you mean that **ideally** the 2D Graphics API _should_ or _should not_  be integrated into libraries (e.g. libstdc++/libc++) which implement the STL?

If it is to be integrated, you need to create an interface class or you may inadvertently be insisting on there being a common target surface for any particular platform or have significantly limited support for targets surfaces.  Linux has **many** target surfaces, so this is extremely important.

If it's not integrated then you have lots of code duplication which can easily result in mysterious bugs between implementations.  It also means it has little to do with the STL and thus should be an independent specification.

> The intention with it is to avoid delving into whether the program is running on a windowing environment

That's fine... but it sure sounds like you are expecting there to be a single target surface for graphics output.  This is problematic because in Linux, you might be executing in a virtual console, X11, Wayland, Mir or one of the many other obscure environments all with their own implementation requirements.

If the render backend is integrated into the STL and your STL implementation doesn't support your target (e.g. Linux framebuffer) that you are SOL until you edit and recompile libstdc++/libc++ which is no small feat.  Furthermore, it means many people need to collaborate just to get their particular target surface official supported by the STL implementers which is highly problematic.

A way to prevent these situations is to make an interface class that each target can implement on their own.  This way, you can link to the library supporting any target surface without recompiling the STL.

**Comment by mikebmcl** [comment]
>> ... the details of the implementation are left up to library vendors...

> Do you mean that ideally the 2D Graphics API should or should not be integrated into libraries (e.g. libstdc++/libc++) which implement the STL?

First, this is targeted towards becoming a TS. It'll be several years before the question of incorporating it into the C++ Standard Library needs to be addressed.

That said, I'm not sure I understand the distinction you are trying to make between "integrated" and "not integrated". It is integrated to the extent that the headers are included. It is not integrated in that, just like the C runtime, it will probably be a separate module (likely a shared library in environments that support them). But even that is an implementation detail.

> If it is to be integrated, you need to create an interface class or you may inadvertently be insisting on there being a common target surface for any particular platform or have significantly limited support for targets surfaces. Linux has many target surfaces, so this is extremely important.

> If it's not integrated then you have lots of code duplication which can easily result in mysterious bugs between implementations. It also means it has little to do with the STL and thus should be an independent specification.

All functions, including member functions, in the proposal are just interface specifications. Indeed, every function contained in the STL in the ISO C++ Standard is just an interface specification. Some aspects must be integrated in that class and function template definitions must reside in header files. But even in those cases, how they are actually implemented is intentionally not specified. Each implementation of the STL gets to decide how to implement e.g., the std::string class template, so long as their implementation conforms to the interface specifications contain in the Standard.

There is no intention, nor requirement, that the display_surface target only one target surface. That said, the specification makes no mention of the potential for multiple possible targets. As such, a mechanism for choosing a particular output (or ranking them in order of preference) would need to be an implementation extension. There is no way to portably specify that, but an informative note would be a good idea.

That said, an implementation that targets Unix and Unix-like environments might be written as follows:

1. Determine if the program is launching in a console.
2. If yes, determine if the console is running within the context of a windowing environment (e.g. Xterm). If yes, proceed to the next step, if no, determine if there is a supported graphics backend for the console and if so create a display_surface using that, otherwise terminate.
3. Determine the windowing environment and if it is supported. create a display_surface for it. If not, sequentially attempt to create a display_surface using each of the supported windowing environments. If one succeeds, (likely due to an emulation layer for a supported windowing environment along the lines of XWayland, though I expect that Wayland would be one of the supported windowing environments), cease the sequential search and use the successful attempt as the display_surface. Otherwise terminate.

This approach would rely on the operating environment supporting runtime loading of shared libraries. Systems that don't support shared libraries or don't support runtime loading of them using something like `dlopen()` would need to follow a different approach. This is not a problem since the target environment is known (or knowable) at compile time.

Note that this issue applies to Microsoft Windows as well, since the use of DirectX (the likely first choice backend) over Remote Desktop Protocol and in Hyper-V instances depends on the operating environment (RemoteFX, hardware requirements, and the OS version). This also applies to OpenGL (see [this blog post about Server 2016](https://blogs.technet.microsoft.com/enterprisemobility/2014/11/05/remotefx-vgpu-updates-in-windows-server-next/). As such, there would need to be a "fallback" GDI implementation if DirectX (or OpenGL, depending on the implementation) was not available. And if the app was a UWP app then fallback would be impossible (GDI isn't available in UWP apps) and so the attempt to create a display_surface would fail and the app would terminate.

> If the render backend is integrated into the STL and your STL implementation doesn't support your target (e.g. Linux framebuffer) that you are SOL until you edit and recompile libstdc++/libc++ which is no small feat. Furthermore, it means many people need to collaborate just to get their particular target surface official supported by the STL implementers which is highly problematic.

> A way to prevent these situations is to make an interface class that each target can implement on their own. This way, you can link to the library supporting any target surface without recompiling the STL.

Implementations always have to pick which operating environments they support. This is true even for implementing aspects of the STL that might seem simple such as console I/O, file streams, the new filesystem API in C++17. and even memory allocation.

So the statement "(if) your STL implementation doesn't support your target (e.g. Linux framebuffer) that you are SOL" can be simplified to "if your STL implementation doesn't support your target then you are SOL".

Many people have had to collaborate to get their particular target OS officially supported by various STL implementations. Implementing the Transactional Memory TS for various STL implementations and OSs they support will take collaboration and time by people who want it on a target platform. This will also be true for the Networking TS, which is expected to go to publication after the C++ committee meeting this July in Toronto (it passed its formal balloting so there is only a small bit of work left to do on it). And various other TSs that have been published or will be published in the near future.

I realize and recognize that implementations of 2D Graphics (if/when it becomes a TS) will almost certainly involve more work than other TSs. But questions such as those and whether this should even be standardized would essentially require their own paper. Which is on my todo list.

For now, excluding the question of whether this has any place in the STL (or is even worth pursing as a TS), I hope I've answered your questions. If not, let me know.

**Comment by GravisZro** [comment]
> That said, an implementation that targets Unix and Unix-like environments might be written as follows:

Yes, that is the exact monolithic design that I feared you were leaning toward.  My suggestion is that instead of having one implementation (per platform) to rule them all that instead you abstract the rendering interface.  This would allow third-party libraries to implement their own rendering and in turn drastically improve portability.  It would also be possible to integrate into APIs (e.g. Qt) because you would be able to restrict the drawing to a specified surface rather than the entire display.


> Many people have had to collaborate to get their particular target OS officially supported by various STL implementations.

It's precisely because of the massive amount of effort to add specialization that it should be abstracted.  An abstraction would allow you to describe the operations you wish to have done using this 2D Graphics API while having a third-library implement the actual rendering independently without all the hassle involved in getting it officially supported.

**Comment by mikebmcl** [comment]
The Standard Library is an interface. Various people implement it for various platforms. I don't see the distinction between saying that 2D graphics is a monolithic design and saying that std::vector is a monolithic design as you are describing it.

Third party libraries can implement any aspect of the STL or of any TS and can make those implementations available both to STL implementers and to the public at large.

If you're talking about an entirely polymorphic design, with everything being abstract virtual functions, I'd be happy to give you advice (I'm quite serious) about how to write a proposal and submit it the WG21 (the "C++ committee") for consideration.

The mere fact that I and my co-authors are working on this proposal in no way prevents anyone else from drafting and proposing a paper on the same subject matter that offers a different model for doing things. In fact you need not even go to those lengths. Papers that propose modifications to other papers are not uncommon, so you could also draft a paper of that nature.

My hypothetical implementation was just that, by the way: hypothetical. The only things that any standardized C++ library, whether it is in the Standard itself or is in a TS, lays out is an interface. You state that my hypothetical implementation is a monolithic design. Ignoring the fact that it was hypothetical and that I do not write STL implementations for a living, could you explain what you mean? When I see monolithic mentioned in the context of GNU/Linux, my mind leaps to the very old debate regarding the design of the Linux kernel versus the design of both GNU/Hurd and MINIX (i.e. the monolithic kernel vs. microkernel debate).

I've said it multiple times I believe but I feel I must say it again. Whether it's the std::basic_string class template, the filesystem API, the algorithms API, the Networking TS, or anything else, the only thing specified is interface.

Without some examples in which you cite sections of the R4 paper and tell me what your concerns are and what you'd like to see instead, I am out of ideas and as such will close this issue within the next few days. I'm afraid we are going around in circles and without some concrete examples I will not be able to address or at least answer your concerns.

**Comment by jube** [comment]
I think what @GravisZro means by interface is polymorphic interface (like Java interface). That said, he is totally right: you can not provide a drawing API and no mean to use that API. And no, it's not "implementaton defined" because in that case, you would be able to draw on the implementer's surface, not the surface you want. Instead, with a polymorphic interface, any vendor could provide its own implementation of a surface. In its current form, the proposal is totally useless because you can not _choose_ on which surface you want to draw.

**Comment by GravisZro** [comment]
It's come to my attention that usage of the term "interface class" could be confused in this context.  I'm specifically referring to a class with all pure virtual functions.

**Comment by mikebmcl** [comment]
Ah, so a pure abstract class. That does clear it up.

There are benefits and drawbacks to such a design.

The major benefit is essentially as you've described it. The surface class would consist entirely of customization points (i.e. the pure virtual functions). As per [derived.classes] in the C++ standard, "[v]irtual member functions signatures defined for a base class in the C++ standard library may be overridden in a derived class defined in the program." (I'm using the stable name rather than the section number because the section numbers have changed between C++14 and the current working draft (i.e. it used to be 17.6.4.5 and now is 20.5.4.5)). Note that it would still be forbidden for the derived class to reside in the std namespace or any of its nested namespaces; see [namespace.std].

So anyone could create an implementation of it simply by deriving from surface. The same change could be made to image_surface and display_surface.

But that major benefit is also the major drawback. Since all implementations would consist of derived classes, users would have no idea of what name those derived classes would have nor what namespace they would be in. Any attempt to try to define specific names and a namespace would never be adopted by the committee. Allowing such customizations into namespace std would also fail. (I don't have time to write out all of the reasons that either proposition would be a non-starter so you're just going to have to take my word for it or verify it for yourself by talking with other people who participate in C++ standardization).

And so we'd lose a major benefit of standardization since users would need to litter their code with macros that would conditionally include the various header files for each implementation they wanted to support and then to use the correct class names and namespaces that each implementation has independently decided on.

They'd also need to worry about whether or not each implementation created an ABI break in an updated version and would have to worry about how to handle it if they did (either force the use of a specific version or else create separate builds for each version).

And if they wanted to try to use a hardware-accelerated implementation and then fall back to some other software implementation, there's no way to guard against name collision (both for headers and within namespaces).

In the end, it would be a nightmare that would be cloaked in the false guise of being a standard.

It would be far easier for platform vendors to simply create an implementation of this API and make it available to standard library vendors.

@jube 

> And no, it's not "implementaton defined" because in that case, you would be able to draw on the implementer's surface, not the surface you want.

As I mentioned in an earlier post, this is a known issue - https://github.com/mikebmcl/io2dts/issues/6 . The existing API  It's a difficult problem and getting the right solution is more valuable than getting any solution. For the reasons I set forth above, polymorphism isn't the answer.

The answer also isn't going to be found in the display_surface class; that exists for users who just want to write some simple code that will display graphics and manage any internal details (e.g. an event loop) for them. The plan from the beginning has been to first do the graphical output part and after that to then do the input to that graphical output part. So eventually there will be a class that derives from that which will be called something like "io_surface" which will then provide a fully-functional simple API.

But letting users harness this API to draw to an existing graphical output (where they manage the internal details such as an event loop) is also a goal; it's just one that hasn't come together yet. Even without that, the API as it stands is useful in teaching (especially introductory programming classes) and for basic graphics operations (you could use image_surface to create and save charts, graphs, etc., and display_surface would also provide some benefits). Text rendering is coming, btw. It is also a difficult problem and so it will be proposed separately as a modification to this when it is ready.

I'm closing this issue now. I am not persuaded to make the requested change for the reasons I stated as drawbacks above. But just because I'm not convinced to make this change doesn't mean it can't happen. It just means that someone who wants it would need to draft a proposal, present it at a C++ committee meeting (see isocpp.org for details about all of that), and convince people that the change should be made (in which case I would make it).
